import { Suspense } from "react"
import AuthLayoutClient from "./layout.client"
import localFont from "next/font/local"

// Define fonts at the server component level
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata = {
  title: "Dormitory website",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <AuthLayoutClient>{children}</AuthLayoutClient>
        </Suspense>
      </body>
    </html>
  )
}

